import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/header";
import { Vazirmatn } from "next/font/google";
import { ThemeProvider } from "@/provides/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" className={`${vazirmatn.variable} font-sans`}>
      <body className="bg-bg text-text transition-colors">
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
