import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/layout/header";
import { Vazirmatn } from "next/font/google";
import { ThemeProvider } from "@/provides/theme-provider";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "شرکت فنی و مهندسی طاق",
  description: "Generated by create next app",
   icons: {
    icon: "/images/icon/tagh-logo-knauf-large.png", 
  },
};

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className={`${vazirmatn.variable} font-sans`}>
      <body className="bg-bg text-text transition-colors  relative">
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
